// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oWDghmqiESffu2X2JKkYC1
// Component: Aua649Lgn9Cmfj

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: oWDghmqiESffu2X2JKkYC1/projectcss
import sty from "./PlasmicRatings.module.css"; // plasmic-import: Aua649Lgn9Cmfj/css

import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: Q6de02ui_Fv_cV/icon

export type PlasmicRatings__VariantMembers = {
  stars: "zero" | "one" | "two" | "three" | "four" | "five";
};
export type PlasmicRatings__VariantsArgs = {
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
};
type VariantPropType = keyof PlasmicRatings__VariantsArgs;
export const PlasmicRatings__VariantProps = new Array<VariantPropType>("stars");

export type PlasmicRatings__ArgsType = {
  numReviews?: React.ReactNode;
};
type ArgPropType = keyof PlasmicRatings__ArgsType;
export const PlasmicRatings__ArgProps = new Array<ArgPropType>("numReviews");

export type PlasmicRatings__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultRatingsProps {
  numReviews?: React.ReactNode;
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRatings__RenderFunc(props: {
  variants: PlasmicRatings__VariantsArgs;
  args: PlasmicRatings__ArgsType;
  overrides: PlasmicRatings__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "stars",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.stars
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries,
    $refs
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant($state, "stars", "five"),
          [sty.rootstars_four]: hasVariant($state, "stars", "four"),
          [sty.rootstars_one]: hasVariant($state, "stars", "one"),
          [sty.rootstars_three]: hasVariant($state, "stars", "three"),
          [sty.rootstars_two]: hasVariant($state, "stars", "two"),
          [sty.rootstars_zero]: hasVariant($state, "stars", "zero")
        }
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(hasVariant($state, "stars", "zero") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__ky22O, {
              [sty.svgstars_five__ky22OrGrx8]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_zero__ky22OIhHGl]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__m9Yk, {
              [sty.svgstars_five__m9YkrGrx8]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__m9YkY0N97]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_one__m9YkufLv]: hasVariant($state, "stars", "one"),
              [sty.svgstars_three__m9YkuS65]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__m9YkPgv12]: hasVariant($state, "stars", "two"),
              [sty.svgstars_zero__m9YkIhHGl]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__hGtRl, {
              [sty.svgstars_five__hGtRlrGrx8]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__hGtRlY0N97]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_one__hGtRlufLv]: hasVariant($state, "stars", "one"),
              [sty.svgstars_three__hGtRluS65]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__hGtRlPgv12]: hasVariant(
                $state,
                "stars",
                "two"
              ),
              [sty.svgstars_zero__hGtRlIhHGl]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__mYmRp, {
              [sty.svgstars_five__mYmRprGrx8]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__mYmRpY0N97]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_one__mYmRpufLv]: hasVariant($state, "stars", "one"),
              [sty.svgstars_three__mYmRpuS65]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__mYmRpPgv12]: hasVariant(
                $state,
                "stars",
                "two"
              ),
              [sty.svgstars_zero__mYmRpIhHGl]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__zodaJ, {
              [sty.svgstars_five__zodaJrGrx8]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__zodaJy0N97]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_one__zodaJufLv]: hasVariant($state, "stars", "one"),
              [sty.svgstars_three__zodaJuS65]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__zodaJPgv12]: hasVariant(
                $state,
                "stars",
                "two"
              ),
              [sty.svgstars_zero__zodaJIhHGl]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : hasVariant($state, "stars", "one")
            ? true
            : hasVariant($state, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__lhakc, {
              [sty.svgstars_five__lhakcrGrx8]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__lhakcY0N97]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_one__lhakcufLv]: hasVariant($state, "stars", "one"),
              [sty.svgstars_three__lhakcuS65]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__lhakcPgv12]: hasVariant(
                $state,
                "stars",
                "two"
              ),
              [sty.svgstars_zero__lhakcIhHGl]: hasVariant(
                $state,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : hasVariant($state, "stars", "two")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__woVv0, {
              [sty.svgstars_five__woVv0RGrx8]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__woVv0Y0N97]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_three__woVv0US65]: hasVariant(
                $state,
                "stars",
                "three"
              ),
              [sty.svgstars_two__woVv0Pgv12]: hasVariant($state, "stars", "two")
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : hasVariant($state, "stars", "three")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__en8Cy, {
              [sty.svgstars_five__en8CyrGrx8]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__en8CyY0N97]: hasVariant(
                $state,
                "stars",
                "four"
              ),
              [sty.svgstars_three__en8CyuS65]: hasVariant(
                $state,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant($state, "stars", "five")
            ? true
            : hasVariant($state, "stars", "four")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__niPq6, {
              [sty.svgstars_five__niPq6RGrx8]: hasVariant(
                $state,
                "stars",
                "five"
              ),
              [sty.svgstars_four__niPq6Y0N97]: hasVariant(
                $state,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant($state, "stars", "five") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__d0Wvh, {
              [sty.svgstars_five__d0WvHrGrx8]: hasVariant(
                $state,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>
      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews)
      })}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRatings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRatings__VariantsArgs;
    args?: PlasmicRatings__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRatings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicRatings__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicRatings__ArgProps,
          internalVariantPropNames: PlasmicRatings__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
